[34m[1mwandb[39m[22m:   5 of 5 files downloaded.
/Users/keanl/miniforge3/lib/python3.10/random.py:370: DeprecationWarning: non-integer arguments to randrange() have been deprecated since Python 3.10 and will be removed in a subsequent version
  return self.randrange(a, b+1)
Traceback (most recent call last):
  File "/Users/keanl/Desktop/Computer_Science/Comp_775/project/Comp775Project/train_segment_afa.py", line 41, in <module>
    main()
  File "/Users/keanl/Desktop/Computer_Science/Comp_775/project/Comp775Project/train_segment_afa.py", line 37, in main
    model = tf.keras.models.load_model(unet_artifact_dir)
  File "/Users/keanl/miniforge3/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/keanl/miniforge3/lib/python3.10/site-packages/tensorflow/python/framework/type_spec.py", line 469, in _deserialize
    return cls(*serialization)  # pytype: disable=not-instantiable  # trace-all-classes
TypeError: VariableSpec.__init__() takes from 2 to 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "/Users/keanl/Desktop/Computer_Science/Comp_775/project/Comp775Project/train_segment_afa.py", line 41, in <module>
    main()
  File "/Users/keanl/Desktop/Computer_Science/Comp_775/project/Comp775Project/train_segment_afa.py", line 37, in main
    model = tf.keras.models.load_model(unet_artifact_dir)
  File "/Users/keanl/miniforge3/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/keanl/miniforge3/lib/python3.10/site-packages/tensorflow/python/framework/type_spec.py", line 469, in _deserialize
    return cls(*serialization)  # pytype: disable=not-instantiable  # trace-all-classes
TypeError: VariableSpec.__init__() takes from 2 to 4 positional arguments but 5 were given